### ISSUE TITLE
360.cn will not archive to IA 

### ISSUE THREAD

**Issue by bunnybooboo** [jonathanKingston/fix-my-http#11]
Running through a top 50 global website list. This site will not load through Internet Archive so breaks the access to the site. Comes up as 

> Sorry. This url has been excluded from the wayback machine.

**Comment by jonathanKingston** [comment]
I have seen this message before, it seems a variant of the "excluded from the wayback machine" I'm not sure if these should be retried a few times like the "Bummer." message that is handled here https://github.com/jonathanKingston/fix-my-http/blob/052068d2e2b660826525545b8897b578fea6ba0a/contentScripts/archiveUsability.js#L34
Or if it should be handled like the robots.txt exclusion auto loading it in the Jail (This auto loading of the jail in the future may require a user approval).

**Comment by bunnybooboo** [comment]
Ahh right, see what you mean. Works today anyways.
