### ISSUE TITLE
ebay "page isn't redirecting properly"

### ISSUE THREAD

**Issue by bunnybooboo** [jonathanKingston/fix-my-http#12]
ebay.com attempts around 12 redirects but even before it hits this limit it throws 

> page isn't redirecting properly

 error. Nothing obvious to me causing these 301's

**Comment by jonathanKingston** [comment]
My latest nightly isn't reproducing this, are the redirects in the HTTP Jail or not?

Latest code goes straight to archive.org index of this.

**Comment by bunnybooboo** [comment]
Now works for me
