### ISSUE TITLE
weibo gets to sandbox but hits a redirect error

### ISSUE THREAD

**Issue by bunnybooboo** [jonathanKingston/fix-my-http#13]
weibo.com strikes many 301's before shifting to sandbox and throwing the 

> The page isn't redirecting properly

**Comment by jonathanKingston** [comment]
I don't see this either however I have seen this error. Pages within the site when loaded through archive.org at least show a modal that covers the page with 2017 and a close button.

**Comment by bunnybooboo** [comment]
Meh. I only did these few errors as it kept doing it. Again, now works for me. All good.
